name: Windows Binaries

on:
  push:
  release:
    types: ['released', 'prereleased']

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install Eigen
      shell: powershell
      run: ./scripts/install-eigen.ps1 RelWithDebInfo
      env:
        VIRTUAL_ENV: Eigen-install
    - name: Configure
      shell: powershell
      run: |
        cmake -B package -S QPALM `
          -D BUILD_SHARED_LIBS=On `
          -DCMAKE_POSITION_INDEPENDENT_CODE=On `
          -DQPALM_WITH_CXX=On `
          -DQPALM_WITH_FORTRAN=Off
      env:
        CMAKE_PREFIX_PATH: Eigen-install
    - name: Build Debug
      shell: powershell
      run: |
        cmake --build package --config Debug -j
    - name: Build Release
      shell: powershell
      run: |
        cmake --build package --config RelWithDebInfo -j
    - name: Package
      shell: powershell
      run: |
        cpack -C "Debug;RelWithDebInfo" `
          -D CPACK_INSTALL_CMAKE_PROJECTS=".;QPALM;ALL;/;LADEL;LADEL;ALL;/" `
          -G "ZIP"
      working-directory: package
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: qpalm-windows
        path: package/QPALM-*-win64.zip

  test:
    needs: [build]
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install Eigen
      shell: powershell
      run: ./scripts/install-eigen.ps1 RelWithDebInfo
      env:
        VIRTUAL_ENV: Eigen-install
    - name: Download
      uses: actions/download-artifact@v3
      with:
        name: qpalm-windows
        path: package
    - name: Install
      shell: powershell
      run: |
        Expand-Archive -Path package/QPALM-*-win64.zip `
          -DestinationPath QPALM-install
        mv QPALM-install/QPALM-*-win64 QPALM-install/QPALM
        echo "$pwd\QPALM-install\QPALM\bin" | Out-File -Append -FilePath $Env:GITHUB_PATH
    - name: Build examples (Release)
      shell: powershell
      run: |
        cmake -B build-examples -S examples
        cmake --build build-examples -j --config RelWithDebInfo
      env:
        CMAKE_PREFIX_PATH: "Eigen-install;QPALM-install/QPALM"
    - name: Run examples (Release)
      shell: powershell
      run: |
        ./build-examples/c/RelWithDebInfo/qpalm_demo
        ./build-examples/cxx/RelWithDebInfo/qpalm_demo_cxx
        # ./build-examples/fortran/RelWithDebInfo/qpalm_demo_fortran
    - name: Build examples (Debug)
      shell: powershell
      run: |
        cmake --build build-examples -j --config Debug
      env:
        CMAKE_PREFIX_PATH: "Eigen-install;QPALM-install/QPALM"
    - name: Run examples (Debug)
      shell: powershell
      run: |
        ./build-examples/c/Debug/qpalm_demo
        ./build-examples/cxx/Debug/qpalm_demo_cxx
        # ./build-examples/fortran/Debug/qpalm_demo_fortran

  release:
    if: ${{ github.event.action == 'released' || github.event.action == 'prereleased' }}
    needs: [test]
    runs-on: ubuntu-18.04

    steps:
    - name: Download
      uses: actions/download-artifact@v3
      with:
        name: qpalm-windows
        path: package
    - name: Release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
      with:
        files: package/QPALM-*-win64.zip